<?php include('include/header.php');?>
  <!-- Left side column. contains the sidebar -->
  <?php include('include/leftsidebar.php'); ?>
  <?php
  $ptitle=mysqli_fetch_array(mysqli_query($obj->con,"select title from clients where id=".$_REQUEST['cid']));

          ?>
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        <!-- Pace page -->Lead History of  <a href="clients.php?id=<?php echo $_REQUEST['cid']; ?>"><?php echo $ptitle['title'];?></a>
        <!-- <small>Loading example</small> -->
      </h1>
      <ol class="breadcrumb">
        <li><a href="home.php"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="clients.php"><i class="fa fa-users"></i> Clients Management</a></li>

        <li class="active">Lead History</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Main content -->
      <section class="content">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <div class="box">

                       <!-- /.box-header -->
                       <div class="box-body table-responsive">
                         <table id="example2" class="table table-hover table-striped">
                           <thead>
                             <tr>
                            <!-- <th><input type="checkbox" onclick="javascript:checkAll(this);">&nbsp;&nbsp;All</th> -->
                            <th>id</th>
                            <th>Code</th>
                            <th>Proposal For</th>
                            <th>Lead Source</th>
                            <th>Creation Date</th>
                            <th>Total Follow Ups</th>
                            <th>Last Follow Ups</th>
                            <th>Generated By</th>
                            <th>Lead Status/th>
                              <th>last Update</th>
                        <th>follow up</th>
                       <th>Status</th>
                        <th>Action</th>
                           </tr>
                           </thead>
                           <?php
                   $id=$_REQUEST['cid']??'';
                   $where= array(
                   "client_id" => $id,
                   );
                   $myrow = $obj->fetch_all_record("leads",$where);
                   if($myrow != null) {
                   foreach ($myrow as $row) {
                     $c=mysqli_fetch_assoc(mysqli_query($obj->con,"select * from clients where id=".$row['client_id']));
                     $pfor=mysqli_fetch_assoc(mysqli_query($obj->con,"select * from services where id=".$row['service_id']));
                     $fcount=mysqli_fetch_assoc(mysqli_query($obj->con,"select count(*) as allcount from follow_ups where lead_id='".$row['id']."'"));
                     $f=mysqli_fetch_assoc(mysqli_query($obj->con,"select * from follow_ups where lead_id='".$row['id']."' order by id desc limit 1"));
                     $generated_by=mysqli_fetch_assoc(mysqli_query($obj->con,"select * from system_users where id='".$row['generated_by']."'"));
                     $followups='<a href="followups.php?lid='.$row['id'].'" class="btn btn-success btn-xs"> <i class="fa fa-plus"></i></a>&nbsp; <a href="followups.php?lid='.$row['id'].'&m=active" class="btn btn-primary btn-xs"> <i class="fa fa-eye"></i></a>';

                $c_at= date_format(date_create($row['created_at']),'d-M-Y');
                $u_at= $row['updated_at'] != null ? date_format(date_create($row['updated_at']),'d-M-Y') : $c_at;

               $last_update='<p class="text-danger">Created At: '.$c_at.'</p> <p class="text-success">Last Update At: '.$u_at.'</p>';
               $sts=$row['status'] != 0 ? '<small class="label bg-green1">Active</small>': '<small class="label bg-red1">Inactive</small>';
               $fdate=date_format(date_create($f['last_followup']),'d-M-Y');


                 ?>
                           <tbody id="tbody">
                             <td><?php echo $row['id']; ?></td>
                             <td><?php echo $row['lead_code']; ?></td>
                             <td><?php echo $pfor['title']; ?></td>
                             <td><?php echo $row['lead_source']; ?></td>
                             <td><?php echo $row['date']; ?></td>
                             <td><?php echo $fcount['allcount']; ?></td>
                             <td><?php echo $fdate; ?></td>
                             <td><?php echo $generated_by['name']; ?></td>
                             <td><?php echo '<span class="label bg-rainbow1">'.$row['lead_status'].'</span>'; ?></td>
                             <td><?php echo $last_update; ?></td>
                             <td><?php echo $followups; ?></td>
                             <td><?php echo $sts; ?></td>
                             <td><a href="leads.php?id=<?php echo $row['id'];?>" style="cursor:pointer;" class="btn btn-primary btn-xs" ><i class="fa fa-edit" ></i></a>
</td>
                           </tbody>
                      <?php

                    }
                  }
                      ?>
                             <tfoot>
                             <tr>
                              <th>id</th>
                              <th>Code</th>
                              <th>Proposal For</th>
                              <th>Lead Source</th>
                              <th>Creation Date</th>
                              <th>Total Follow Ups</th>
                              <th>Last Follow Ups</th>
                              <th>Generated By</th>
                              <th>Lead Status/th>
                                <th>last Update</th>
                          <th>follow up</th>
                             <th>Status</th>
                              <th>Action</th>
                           </tr>
                           </tfoot>
                         </table>
                       </div>
                       <!-- /.box-body -->
                  </div>
          </div>
        </div>
  </section>

          <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <?php include('include/footer.php');?>
  <script>
  function 	RefreshView() {
  	self.location="clientleads.php?m=active&cid=<?php echo $_REQUEST['cid']; ?>";
}
$(function () {
$('#example2').DataTable({
   "order": [[ 0, "desc" ]],
  "columnDefs": [
           {
               "targets": [ 0 ],
               "visible": false,
               "searchable": false
           }
       ]
});
});
  </script>
